curl -H "Content-Type: application/json" -X POST -d '{"balance": "1500", "name": "savings"}' "http://localhost:3000/accounts"

//gets account data

curl "http://localhost:3000/accounts"

//updates account data at specific id, NOTE: replace 'id' in "http://localhost:3000/accounts/5a8d1aba7c79fe2fd35403cd" with the id generated by the previous POST command

curl -H "Content-Type: application/json" -X POST -d '{"balance": "1500"}' "http://localhost:3000/accounts/5a8d1b337c79fe2fd35403d3"

//deletes account data at specific id, NOTE: replace 'id' in "http://localhost:3000/accounts/5a8d1aba7c79fe2fd35403cd" with the id generated by the previous POST command

curl -X DELETE "http://localhost:3000/posts/5a8d1b337c79fe2fd35403d3"